[package]
name = "ruzito"
version = "0.1.0"
authors = ["Cem Ã–zden <cemozden.tr@gmail.com>"]

[dependencies]
clap = "2.33.3"
byteorder = "1.3.4"
inflate = "0.4.5"
crc = "1.8.1"
cli-table = "0.4"
rpassword = "5.0.0"
rust-crypto = "^0.2"
aes-ctr = "0.6.0"